addi x1,x1,1    #x1=1
nop
nop
nop
nop
add x2,x1,x1    #x2=2
nop
nop
nop
nop
slli x2,x1,2    #x2=4
nop
nop
nop
nop
srli x2,x2,1    #x2=2
nop
nop
nop
nop
addi x1,x1,-3   #x1=-2
nop
nop
nop
nop
sub x2,x2,x0    #x2=2
nop
nop
nop
nop
slt x3,x1,x2    #x3=1
nop
nop
nop
nop
sltu x4,x1,x2   #x4=0
nop
nop
nop
nop
srai x1,x1,2    #x1=-1
nop
nop
nop
nop
addi x1,x1,10   #x1=9
nop
nop
nop
nop
sll x2,x2,x1    #x2=1024
nop
nop
nop
nop
srl x2,x1,x2    #x1=9
nop
nop
nop
nop
xori x3,x3,3    #x3=2
nop
nop
nop
nop
sra x3,x3,x1    #x3=0
nop
nop
nop
nop
xor x3,x3,x3    #x3=0
nop
nop
nop
nop
ori x3,x3,3     #x3=3
nop
nop
nop
nop
or  x3,x3,x2    #x3=11
nop
nop
nop
nop
and x3,x3,x2    #x3=9
nop
nop
nop
nop
andi x3,x3,5    #x3=1
nop
nop
nop
nop
lui x5,32       #x5=0x00020000
nop
nop
nop
nop
auipc x6,3      #x6=12688
nop
nop
nop
nop
xor x1,x1,x1    #x1=0
nop
nop
nop
nop
xor x2,x2,x2    #x2=0

